In [112]:
import numpy as np
import pandas as pd
df=pd.read_csv("HepatitisCdata.csv")

In [113]:
df.shape

(615, 14)

In [114]:
# Verisetindeki boş değerlerin sayısı
df.isnull().sum()

Unnamed: 0     0
Category       0
Age            0
Sex            0
ALB            1
ALP           18
ALT            1
AST            0
BIL            0
CHE            0
CHOL          10
CREA           0
GGT            0
PROT           1
dtype: int64

In [115]:
#Verisetindeki kullanılmayan sütun silindi
df.drop("Unnamed: 0", inplace=True, axis= 1)

In [116]:
#Kategorik veriler yine kategorik ancak sayı türündeki kategorik verilere dönüştürüldü.
df['Category'] = df['Category'].replace({'0=Blood Donor': 'Normal', '0s=suspect Blood Donor':'Normal' , '1=Hepatitis': "Hepatitis", '2=Fibrosis': "Fibrosis", '3=Cirrhosis': "Cirrhosis"})
df['Sex'] = df['Sex'].replace({'m': 1, 'f': 0})

In [117]:
df.head()

,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT
0,Normal,32,1,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0
1,Normal,32,1,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5
2,Normal,32,1,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3
3,Normal,32,1,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7
4,Normal,32,1,39.2,74.1,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7

In [137]:
#Verisetindeki tahlil değerlerini 0 veya 1 olarak etiketlenmesi için değer aralıklarına göre işlemler yapıldı.
conditions = [
    (df['ALT'] > 56),
    (df['ALT'] <= 56) & (df['ALT'] >= 7),
    (df['ALT']<7)
    ]
values = [1,0,1]
df['ALT_MAP'] = np.select(conditions, values)

conditions = [
    (df['AST'] > 40),
    (df['AST'] <= 40) & (df['AST'] >= 10),
    (df['AST']<10)
    ]
values = [1,0,1]
df['AST_MAP'] = np.select(conditions, values)

conditions = [
    (df['ALP'] > 147),
    (df['ALP'] <= 147) & (df['ALP'] >= 44),
    (df['ALP']<44)
    ]
values = [1,0,1]
df['ALP_MAP'] = np.select(conditions, values)

conditions = [
    (df['ALB'] > 52),
    (df['ALB'] <= 52) & (df['ALB'] >= 35),
    (df['ALB']<35)
    ]
values = [1,0,1]
df['ALB_MAP'] = np.select(conditions, values)

conditions = [
    (df['BIL'] > 20.5),
    (df['BIL'] <= 20.5) & (df['BIL'] >= 3.4),
    (df['BIL']<3.4)
    ]
values = [1,0,1]
df['BIL_MAP'] = np.select(conditions, values)

conditions = [
    (df['PROT'] > 80),
    (df['PROT'] <= 80) & (df['PROT'] >= 60),
    (df['PROT']<60)
    ]
values = [1,0,1]
df['PROT_MAP'] = np.select(conditions, values)

conditions = [
    (df['GGT'] > 48)&(df['Sex']=='Male'),
    (df['GGT'] <= 48) & (df['GGT'] >= 9) & (df['Sex']=='Male'),
    (df['GGT']<9)&(df['Sex']=='Male'),(df['GGT'] > 32)&(df['Sex']=='Female'),
    (df['GGT'] <= 32) & (df['GGT'] >= 9) & (df['Sex']=='Female'),
    (df['GGT']<9)&(df['Sex']=='Female')
    ]
values = [1,0,1,1,0,1]
df['GGT_MAP'] = np.select(conditions, values)

conditions = [
    (df['CREA'] > 106)&(df['Sex']=='Male'),
    (df['CREA'] <= 106) & (df['CREA'] >= 53) & (df['Sex']=='Male'),
    (df['CREA']<53)&(df['Sex']=='Male'),(df['CREA'] > 97)&(df['Sex']=='Female'),
    (df['CREA'] <= 97) & (df['CREA'] >= 44) & (df['Sex']=='Female'),
    (df['CREA']<44)&(df['Sex']=='Female')
    ]
values = [1,0,1,1,0,1]
df['CREA_MAP'] = np.select(conditions, values)

conditions = [
 (df['CHOL'] > 5.2),
    (df['CHOL']<=5.2)
    ]
values = [1,0]
df['CHOL_MAP'] = np.select(conditions, values)

conditions = [
 (df['CHOL'] > 5.2),
    (df['CHOL']<=5.2)
    ]
values = [1,0]
df['CHOL_MAP'] = np.select(conditions, values)

conditions = [
    (df['CHE'] > 12),
    (df['CHE'] <= 12) & (df['CHE'] >= 5),
    (df['CHE']<5)
    ]
values = [1,0,1]
df['CHE_MAP'] = np.select(conditions, values)

In [138]:
df.head()

,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,...,ALT_MAP,AST_MAP,ALP_MAP,ALB_MAP,BIL_MAP,PROT_MAP,GGT_MAP,CREA_MAP,CHOL_MAP,CHE_MAP
0,0,32,1,38.5,52.5,7.7,22.1,7.5,6.93,3.23,...,0,0,0,0,0,0,0,0,0,0
1,0,32,1,38.5,70.3,18.0,24.7,3.9,11.17,4.80,...,0,0,0,0,0,0,0,0,0,0
2,0,32,1,46.9,74.7,36.2,52.6,6.1,8.84,5.20,...,0,1,0,0,0,0,0,0,0,0
3,0,32,1,43.2,52.0,30.6,22.6,18.9,7.33,4.74,...,0,0,0,0,0,0,0,0,0,0
4,0,32,1,39.2,74.1,32.6,24.8,9.6,9.15,4.32,...,0,0,0,0,0,0,0,0,0,0

In [151]:
#Etiketli verideki sözel olan kategorik değerler sayısal kategorik değerlere dönüştürüldü.
label_mapping = {
    'Normal': 0,
    'Cirrhosis': 1,
    'Fibrosis': 2,
    'Hepatitis': 3
}


df['Category'] = df['Category'].replace(label_mapping)

In [152]:
#Etiketli veri Y değişkenine aktarıldı.
Y = df["Category"]

In [153]:
#Makine Öğrenmesi algoritmalarına gönderilecek olan eğitim verileri X değişkenine aktarıldı.
X=df[["ALT_MAP","AST_MAP","ALP_MAP","ALB_MAP","BIL_MAP","PROT_MAP","GGT_MAP","CREA_MAP","CHOL_MAP","CHE_MAP"]]

In [154]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier 
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

classifierKNN = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p = 2)
classifierKA = DecisionTreeClassifier(criterion = 'entropy', random_state=0)
classifierLG = LogisticRegression(random_state = 0)
classifierRF=RandomForestClassifier(n_estimators=100)

In [155]:
classifierKNN.fit(X_train,y_train)
y_predKNN=classifierKNN.predict(X_test)
from sklearn.metrics import confusion_matrix
cmKNN = confusion_matrix(y_test, y_predKNN)
print(cmKNN)
import sklearn.metrics as mt
print(mt.accuracy_score(y_test,y_predKNN))

[[137   2   0   0]
 [  3   4   0   0]
 [  1   1   2   0]
 [  3   0   1   0]]
0.9285714285714286

In [156]:
classifierKA.fit(X_train,y_train)
y_predKA=classifierKA.predict(X_test)
from sklearn.metrics import confusion_matrix
cmKA = confusion_matrix(y_test, y_predKA)
print(cmKA)
import sklearn.metrics as mt
print(mt.accuracy_score(y_test,y_predKA))

[[136   1   1   1]
 [  4   3   0   0]
 [  1   1   2   0]
 [  3   0   1   0]]
0.9155844155844156

In [157]:
classifierLG.fit(X_train,y_train)
y_predLG=classifierLG.predict(X_test)
from sklearn.metrics import confusion_matrix
cmLG = confusion_matrix(y_test, y_predLG)
print(cmLG)
import sklearn.metrics as mt
print(mt.accuracy_score(y_test,y_predLG))

[[135   4   0   0]
 [  5   2   0   0]
 [  1   1   2   0]
 [  2   0   1   1]]
0.9090909090909091

In [158]:
classifierRF.fit(X_train,y_train)
y_predRF=classifierRF.predict(X_test)
from sklearn.metrics import confusion_matrix
cmRF = confusion_matrix(y_test, y_predRF)
print(cmRF)
import sklearn.metrics as mt
print(mt.accuracy_score(y_test,y_predRF))

[[136   2   0   1]
 [  4   3   0   0]
 [  1   1   2   0]
 [  3   0   1   0]]
0.9155844155844156

In [159]:
import pickle

filename='KNNModel.sav'

pickle.dump(classifierKNN,open(filename,'wb'))